module.exports = fields => {
    return `
<!-- generated by yi-code -->
    <el-tabs v-model="activeName" @tab-click="handleClick">
        ${fields
            .map(field => {
                return (
                    '<el-tab-pane label="' +
                    field.label +
                    '" name="' +
                    field.prop +
                    '">' +
                    field.label +
                    '</el-tab-pane>'
                );
            })
            .join('\n        ')}
    </el-tabs>
`;
};
