module.exports = fields => {
    return `
<!-- generated by yi-code -->
<template>
  <el-table
    :data="tableData"
    style="width: 100%"
    height=600
    stripe
    border
    :default-sort = "{prop: 'date', order: 'descending'}">
    ${fields
        .map(field => {
            return [
                '<el-table-column',
                '  prop="' + field.prop + '"',
                '  label="' + field.label + '"',
                '  sortable',
                '  width="180">',
                '</el-table-column>\n'
            ].join('\n    ');
        })
        .join('    ')}
  </el-table>
</template>

<style>
</style>

<script>
    export default {
        props: ['tableData']
    }
</script>
`;
};
